"""Initial migration

Revision ID: 8c0d3e8d8c9a
Revises: 8e65a43fe4c6
Create Date: 2025-12-27 11:51:45.653878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0d3e8d8c9a'
down_revision: Union[str, None] = '8e65a43fe4c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'company')
    op.drop_column('projects', 'customer')
    op.drop_column('projects', 'sales_order')
    op.drop_column('projects', 'copied_from')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('copied_from', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('sales_order', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('customer', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
