"""Initial migration

Revision ID: 68695764cca6
Revises: 
Create Date: 2025-12-27 10:38:31.626423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68695764cca6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('docstatus', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_project_categories_name'), 'project_categories', ['name'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('docstatus', sa.Integer(), nullable=True),
    sa.Column('parent', sa.String(length=255), nullable=True),
    sa.Column('parentfield', sa.String(length=255), nullable=True),
    sa.Column('parenttype', sa.String(length=255), nullable=True),
    sa.Column('idx', sa.Integer(), nullable=True),
    sa.Column('naming_series', sa.String(length=50), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('project_type', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=True),
    sa.Column('percent_complete_method', sa.String(length=50), nullable=True),
    sa.Column('percent_complete', sa.Float(), nullable=True),
    sa.Column('project_template', sa.String(length=255), nullable=True),
    sa.Column('expected_start_date', sa.DateTime(), nullable=True),
    sa.Column('expected_end_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('customer', sa.String(length=255), nullable=True),
    sa.Column('sales_order', sa.String(length=255), nullable=True),
    sa.Column('copied_from', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True),
    sa.Column('actual_time', sa.Float(), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_costing', sa.Float(), nullable=True),
    sa.Column('total_costing_amount', sa.Float(), nullable=True),
    sa.Column('total_purchase_cost', sa.Float(), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('total_sales_amount', sa.Float(), nullable=True),
    sa.Column('total_billable_amount', sa.Float(), nullable=True),
    sa.Column('total_billed_amount', sa.Float(), nullable=True),
    sa.Column('total_consumed_material_cost', sa.Float(), nullable=True),
    sa.Column('cost_center', sa.String(length=255), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('per_gross_margin', sa.Float(), nullable=True),
    sa.Column('collect_progress', sa.Integer(), nullable=True),
    sa.Column('holiday_list', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('from_time', sa.String(length=20), nullable=True),
    sa.Column('to_time', sa.String(length=20), nullable=True),
    sa.Column('first_email', sa.String(length=20), nullable=True),
    sa.Column('second_email', sa.String(length=20), nullable=True),
    sa.Column('daily_time_to_send', sa.String(length=20), nullable=True),
    sa.Column('day_to_send', sa.String(length=20), nullable=True),
    sa.Column('weekly_time_to_send', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('rd_template', sa.String(length=255), nullable=True),
    sa.Column('tasks_completed_this_week', sa.Integer(), nullable=True),
    sa.Column('department_migrated', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['project_categories.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('project_users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('docstatus', sa.Integer(), nullable=True),
    sa.Column('parent', sa.String(length=255), nullable=True),
    sa.Column('parentfield', sa.String(length=255), nullable=True),
    sa.Column('parenttype', sa.String(length=255), nullable=True),
    sa.Column('idx', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('view_attachments', sa.Integer(), nullable=True),
    sa.Column('welcome_email_sent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['projects.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_project_users_name'), 'project_users', ['name'], unique=False)
    op.create_table('tasks',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('docstatus', sa.Integer(), nullable=True),
    sa.Column('parent', sa.String(length=255), nullable=True),
    sa.Column('parentfield', sa.String(length=255), nullable=True),
    sa.Column('parenttype', sa.String(length=255), nullable=True),
    sa.Column('idx', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=True),
    sa.Column('issue', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('is_group', sa.Integer(), nullable=True),
    sa.Column('is_template', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('is_important', sa.Integer(), nullable=True),
    sa.Column('task_weight', sa.Float(), nullable=True),
    sa.Column('parent_task', sa.String(length=255), nullable=True),
    sa.Column('completed_by', sa.String(length=255), nullable=True),
    sa.Column('completed_on', sa.DateTime(), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('exp_start_date', sa.DateTime(), nullable=True),
    sa.Column('expected_time', sa.Float(), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('exp_end_date', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('is_milestone', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('depends_on_tasks', sa.Text(), nullable=True),
    sa.Column('act_start_date', sa.DateTime(), nullable=True),
    sa.Column('actual_time', sa.Float(), nullable=True),
    sa.Column('act_end_date', sa.DateTime(), nullable=True),
    sa.Column('total_costing_amount', sa.Float(), nullable=True),
    sa.Column('total_expense_claim', sa.Float(), nullable=True),
    sa.Column('total_billing_amount', sa.Float(), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('closing_date', sa.DateTime(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=True),
    sa.Column('rgt', sa.Integer(), nullable=True),
    sa.Column('old_parent', sa.String(length=255), nullable=True),
    sa.Column('template_task', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['parent_task'], ['tasks.name'], ),
    sa.ForeignKeyConstraint(['project'], ['projects.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_tasks_name'), 'tasks', ['name'], unique=False)
    op.create_table('task_depends_on',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('docstatus', sa.Integer(), nullable=True),
    sa.Column('parent', sa.String(length=255), nullable=True),
    sa.Column('parentfield', sa.String(length=255), nullable=True),
    sa.Column('parenttype', sa.String(length=255), nullable=True),
    sa.Column('idx', sa.Integer(), nullable=True),
    sa.Column('task', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('project', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['tasks.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_task_depends_on_name'), 'task_depends_on', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_depends_on_name'), table_name='task_depends_on')
    op.drop_table('task_depends_on')
    op.drop_index(op.f('ix_tasks_name'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_project_users_name'), table_name='project_users')
    op.drop_table('project_users')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_project_categories_name'), table_name='project_categories')
    op.drop_table('project_categories')
    # ### end Alembic commands ###
