"""add_role_to_project_users

Revision ID: 636d73d2aac6
Revises: 8c0d3e8d8c9a
Create Date: 2025-12-27 12:16:43.378594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636d73d2aac6'
down_revision: Union[str, None] = '8c0d3e8d8c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_users', sa.Column('role', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_users', 'role')
    # ### end Alembic commands ###
